// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {

    public static final class DriveConstants {}

    public static final class IntakeHopperConstants {
        public static final double HopperFloorTransferSecureSpeed = 0.1;
    }

    public static final class TurretShooterConstants {
        public static final int SENSOR_TO_MECH_RATIO = 10;
        
        public static final double MAX_LEFT_POSITION = -0.25;
        public static final double MAX_RIGHT_POSITION = 0.25;
        public static final double NEUTRAL_POSITION = 0;
        public static final double MAX_LEFT_DEGREES = MAX_LEFT_POSITION * 360;
        public static final double MAX_RIGHT_DEGREES = MAX_RIGHT_POSITION * 360;

        public static final double TURRET_CAM_TIMEOUT = 0.5;

        public static final double degreesToRotations(double degrees) {
            return degrees / 360.0;
        }

        public static final double rotationsToDegrees(double rotations) {
            return rotations * 360.0;
        }
    }

    public static final class LEDConstants {
        public static final int LED_PORT = 2;
        public static final int[] LED_LENGTHS = {8};
    }

    public static final class VisionConstants {
        public static final String TURRET_CAM = "limelight-turret";
        public static final double ANGLE_ERROR_THRESHOLD = 3.0;
    }

    public static final class ClimbConstants {
        public static final double raiserUpperTarget = 100.0;
        public static final double raiserLowerTarget = 0.0;

        //public static final double climbUpperLimit = 205.0;
        //public static final double climbLowerLimit = 0.06;
        //public static final double climbSensorLimit = 0;

        public static final double climbCurrentLimit = 25;
    }

}

