// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

import java.util.Optional;

import com.ctre.phoenix6.CANBus;

import edu.wpi.first.apriltag.AprilTagFieldLayout;
import edu.wpi.first.apriltag.AprilTagFields;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide
 * numerical or boolean
 * constants. This class should not be used for any other purpose. All constants
 * should be
 * declared globally (i.e. public static). Do not put anything functional in
 * this class.
 *
 * <p>
 * It is advised to statically import this class (or one of its inner classes)
 * wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {

    public static final class Debug {
        public static final boolean DEBUG_MODE = true;
        public static final boolean INTAKE_ROLLER_EXISTS = true;
        public static final boolean INTAKE_EXTEND_EXISTS = true;
        public static final boolean SHOOTER_SPEED_OVERRIDE = false;
    }

    public static final class DriveConstants {

        public static final double LOCK45_SPEED_MULTIPLIER = 0.5;

        public static final Alliance getAlliance() {
            Optional<Alliance> ally = DriverStation.getAlliance();
            if (ally.isPresent()) {
                return ally.get() == Alliance.Red ? Alliance.Red : Alliance.Blue;
            } else {
                return null;
            }
        }
    } 

    public static final class IntakeHopperConstants {
        // Floor transfer constants
        public static final double HOPPER_FLOOR_TRANSFER_SECURE_SPEED = 0.4;
        public static final double AGITATE_COMMAND_SPEED = 0.4;
       
        public static final double FUEL_GRABBER_SPEED = 1.0;
        // Hopper extend/retract constants
        // public static final double EXTEND_SPEED = -0.25;
        // public static final double RETRACT_SPEED = 0.25;
        // public static final double HOLD_SPEED = -0.05;
        // public static final double EXTEND_TIME_SECONDS = 0.75;
        public static final int CURRENT_LIMIT = 13;
        public static final double RETRACT_POSITION_POSITION = 0;
        public static final double EXTENDED_UP_POSITION_POSITION = -1.7;
        public static final double EXTENDED_DOWN_POSITION_POSITION = -3.4;
        public static final double MOTOR_TOLERANCE = 0.05;
        public static final double HOPPER_ZEROING_SPEED = 0.2;
    }

    public static final class TurretShooterConstants {
        public static final CANBus CAN_BUS = new CANBus("CANivore2");

        public static final int SENSOR_TO_MECH_RATIO = 10;

        public static final double MAX_LEFT_POSITION = -0.3303;
        public static final double MAX_RIGHT_POSITION = 0.1062;
        public static final double NEUTRAL_POSITION = 0;
        public static final double MAX_LEFT_DEGREES = MAX_LEFT_POSITION * 360;
        public static final double MAX_RIGHT_DEGREES = MAX_RIGHT_POSITION * 360;
        public static final double SNOW_BLOWER_POSITION = 45.0;
        // I think this is wrong
        public static final double RESTRICTED_MAX_LEFT_DEGREES = MAX_LEFT_DEGREES;
        public static final double RESTRICTED_MAX_RIGHT_DEGREES = 0.061844 * 360;

        public static final double TURRET_CAM_TIMEOUT = 0.5;

        public static final double MAGAZINE_FORWARD_SPEED = 1.0;
        public static final double GATE_FORWARD_SPEED = 0.3;
        public static final double GATE_REVERSE_SPEED = -0.2;

        public static final double JAM_CLEAR_SPEED = -0.75;
        public static final double TURRET_ZEROING_SPEED = -0.04;
    }

    public static final class LEDConstants {
        public static final int LED_PORT = 2;
        public static final int[] LED_LENGTHS = { 8 };
    }

    public static final class VisionConstants {
        public static final String TURRET_CAM = "limelight-turret";
        public static final double ANGLE_ERROR_THRESHOLD = 3.0;
      
        // This variable assumes the robot is a square
        // TODO: adjust for actual robot dimensions
        public static final double ROBOT_WIDTH_METERS = 0.5;

        public static final String LIMELIGHT_NAME = "limelight";

        // adjust for actual camera position and orientation on the robot
        public static final double[] CAMERA_POSE_ROBOT_SPACE = {
                -0.2855,// X position of camera on robot in meters (positive forward, negative backward)
                -0.2698, // Y position of camera on robot in meters (positive right, negative left)
                0.517, // Z position of camera on robot in meters (positive up, negative down)
                0.0, // Roll of the camera on the robot in degrees
                0.0, // Pitch of the camera on the robot in degrees
                180.0  // Yaw of the camera on the robot in degrees
        };

    }

    public static final class FieldConstants {
        public static final AprilTagFields APRIL_TAG_FIELD = AprilTagFields.k2026RebuiltAndymark;
        public static final AprilTagFieldLayout APRIL_TAG_FIELD_LAYOUT = AprilTagFieldLayout
            .loadField(APRIL_TAG_FIELD);

        public static final double FIELD_WIDTH_METERS = APRIL_TAG_FIELD_LAYOUT.getFieldWidth();
        public static final double FIELD_LENGTH_METERS = APRIL_TAG_FIELD_LAYOUT.getFieldLength();

        public static final int[] TAGS_FOR_AUTO_ALIGNMENT = {15, 16, 31, 32};
        
        public static final int[] TAGS_FOR_POSE_ESTIMATION = {
            // tag numbers --> update for each year with all tags on the field unless there is a reason to not use them
            1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
            11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
            21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
            31, 32
        };

        public static final double BLUE_HUB_CENTER_X = APRIL_TAG_FIELD_LAYOUT.getTagPose(21).get().getX();
        public static final double BLUE_HUB_CENTER_Y = APRIL_TAG_FIELD_LAYOUT.getTagPose(20).get().getY();
        public static final Translation2d BLUE_HUB_CENTER = new Translation2d(BLUE_HUB_CENTER_X, BLUE_HUB_CENTER_Y);

        public static final double RED_HUB_CENTER_X = APRIL_TAG_FIELD_LAYOUT.getTagPose(5).get().getX();
        public static final double RED_HUB_CENTER_Y = APRIL_TAG_FIELD_LAYOUT.getTagPose(10).get().getY();
        public static final Translation2d RED_HUB_CENTER = new Translation2d(RED_HUB_CENTER_X, RED_HUB_CENTER_Y);
        
        public static final Translation2d ALLIANCE_HUB_CENTER = DriveConstants.getAlliance() == Alliance.Red ? RED_HUB_CENTER : BLUE_HUB_CENTER;
    }

    public static final class ClimbConstants {
        public static final double RAISER_UPPER_TARGET = 85.0;
        public static final double RAISER_LOWER_TARGET = 0.0;
        public static final double CLIMB_ZEROING_SPEED = -0.25;
        public static final double CLIMB_CURRENT_LIMIT = 25;
    }
    public static final class ShooterConstants {
        public static final double LOW_SPEED_TARGET = 2125.0;
        public static final double MIDDLE_SPEED_TARGET = 2350.0;
        public static final double HIGH_SPEED_TARGET = 2450.0;
        public static final double SNOWBLOW_SPEED_TARGET = 3000.0;
    }

}
