// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import static edu.wpi.first.units.Units.RotationsPerSecond;
import static edu.wpi.first.units.Units.RotationsPerSecondPerSecond;
import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Volts;

import java.util.concurrent.locks.Lock;

import com.ctre.phoenix6.StatusCode;
import com.ctre.phoenix6.configs.MotionMagicConfigs;
import com.ctre.phoenix6.configs.MotorOutputConfigs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.MotionMagicVoltage;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.NeutralModeValue;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants;
import frc.robot.Constants.ClimbConstants;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class ClimbSubsystem extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private TalonFX raiser;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private DigitalInput armBottomSwitch;
    public double raiserUpperTarget;
    public double raiserLowerTarget; 
    public boolean climbing;
    public boolean isOnTower;
    public int climbStage = 0;
    public int lockdownDriveControl = 1;

    public enum LockdownMode {
        none,
        partial,
        full
    };

    public LockdownMode currentLockdownMode = LockdownMode.none;

    private final MotionMagicVoltage m_motionMagicReq = new MotionMagicVoltage(0).withSlot(0);
    TalonFXConfiguration climbConf = new TalonFXConfiguration();

    /**
    *
    */
    public ClimbSubsystem() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        raiser = new TalonFX(26, TunerConstants.kCANBus);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        armBottomSwitch = new DigitalInput(9);
        raiserUpperTarget = Constants.ClimbConstants.raiserUpperTarget;
        raiserLowerTarget = Constants.ClimbConstants.raiserLowerTarget;
        climbing = false;
        isOnTower = false;

        // Configs
        // CurrentLimitsConfigs climbCurrent = climbConf.CurrentLimits;
        // climbCurrent.StatorCurrentLimit = Constants.ClimbConstants.climbCurrentLimit;
        MotorOutputConfigs climbOutput = climbConf.MotorOutput;
        // climbOutput.Inverted = InvertedValue.CounterClockwise_Positive;
        climbOutput.NeutralMode = NeutralModeValue.Brake;

        climbConf.Slot0.kP = 0.4; // An error of 1 rotation results in 2.4 V output
        climbConf.Slot0.kI = 0.0075; // No output for integrated error
        climbConf.Slot0.kD = 0; // A velocity of 1 rps results in 0.1 V output
        climbConf.Slot0.kS = 0.17558;
        climbConf.Slot0.kV = 0.11202;
        climbConf.Slot0.kA = 0.0024753;

        // climbConf.Slot0.GravityType = GravityTypeValue.Arm_Cosine;

        // // Peak output of 8 V
        climbConf.Voltage.withPeakForwardVoltage(Volts.of(10)).withPeakReverseVoltage(Volts.of(-10));

        MotionMagicConfigs motionMagicOn = climbConf.MotionMagic;
        motionMagicOn.withMotionMagicCruiseVelocity(RotationsPerSecond.of(499))
                .withMotionMagicAcceleration(RotationsPerSecondPerSecond.of(100))
                .withMotionMagicJerk(RotationsPerSecondPerSecond.per(Second).of(0)); // 0 makes it fast

        /* Retry config apply up to 5 times, report if failure */
        StatusCode status = StatusCode.StatusCodeNotInitialized;
        for (int i = 0; i < 5; ++i) {
            status = raiser.getConfigurator().apply(climbConf);
            if (status.isOK())
                break;
        }
        if (!status.isOK()) {
            System.out.println("Could not apply configs, error code: " + status.toString());
        }

        SmartDashboard.putData("Subsystem: Climb", this);
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        SmartDashboard.putBoolean("Arm is raised", climbing);
        SmartDashboard.putBoolean("Arm Bottom Switch is triggered", getBottomSwitch());
        SmartDashboard.putString("Lockdown Stage", currentLockdownMode.name());
        SmartDashboard.putNumber("Climb Stage", climbStage);
        SmartDashboard.putNumber("Height Positions", raiser.getPosition().getValueAsDouble());
        setLockdownMode();
        setLockdownDriveControl();
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void stopClimbing() {
        raiser.set(0);
    }

    public void setUpperPosition() {
        raiser.setControl(m_motionMagicReq.withPosition(raiserUpperTarget));
        // climbing = true;
    }

    public void setLowerPosition() {
        raiser.setControl(m_motionMagicReq.withPosition(raiserLowerTarget));
        // climbing = false;
    }

    public boolean isRaised() {
        return Math.abs(raiser.getPosition().getValueAsDouble() - raiserUpperTarget) < .3;
    }

    public boolean isLowered() {
        return Math.abs(raiser.getPosition().getValueAsDouble() - raiserLowerTarget) < .3;
    }

    public boolean isClimbing() {
        return climbing;
    }

    public boolean toggleClimbing() {
        return climbing = !climbing;
    }

    public boolean getBottomSwitch() {
        return armBottomSwitch.get();
    }

    public void setArmZeroing() {
        if (getBottomSwitch()) {
            raiser.set(0);
        } else {
            raiser.set(-.25);
        }
    }

    public void setRaiserPosition(double position) {
        raiser.setPosition(position);
    }
    
    public boolean setBottom() {
        return climbing = false;
    }

    public boolean setTop() {
        return climbing = true;
    }

    public boolean getIsOnTower() {
        return isOnTower;
    }

    public boolean toggleIsOnTower() {
        return isOnTower = !isOnTower;
    }

    public boolean isOnTower() {
        return isOnTower = true;
    }

    public boolean isNotOnTower() {
        return isOnTower = false;
    }

    public int climbStageReset() {
        return climbStage = 0;
    }

    public int getClimbStage() {
        return climbStage;
    }

    public float getRaiserMaxHeightAsFloat() {
        return (float) ClimbConstants.raiserUpperTarget;
    }

    public float getRaiserPosition() {
        return (float) raiser.getPosition().getValueAsDouble();
    }

    public int getRaiserMaxHeightAsInt() {
        return (int) ClimbConstants.raiserUpperTarget;
    }

    public int getRaiserPositionAsInt() {
        return (int) raiser.getPosition().getValueAsDouble();
    }




    // LOCKDOWN MODE METHODS
    // climb stage increments from 0 to 3, then resets to 0 if above 3
    public int climbStageIncrement() {
        if (climbStage < 3) {
            climbStage += 1;
        } else {
            climbStage = 0;
        }
        return climbStage;
    }

    public LockdownMode getLockdownMode() {
        if (climbStage == 0) {
            return LockdownMode.none;
        } else if (climbStage == 1 || climbStage == 3) {
            return LockdownMode.partial;
        } else {
            return LockdownMode.full;
        }
    }

    public int getLockdownDriveControl() {
        if (climbStage == 0) {
            return lockdownDriveControl = 1;
        } else if (climbStage == 1 || climbStage == 3) {
            return lockdownDriveControl = 1;
        } else {
            return lockdownDriveControl = 0;
        }
    }

    public void setLockdownMode() {
        currentLockdownMode = getLockdownMode();
    }

    public void setLockdownDriveControl() {
        lockdownDriveControl = getLockdownDriveControl();
    }
}