// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.util.Color;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.ColorLED;
import frc.robot.Constants;
import frc.robot.Robot;

public class leds extends SubsystemBase {
    public enum LedColor {
        none,
        red,
        blue,
        green,
        orange,
        gold,
        white,
        purple,
        yellow,
        rainbow
    };

    public LedColor ledColor = LedColor.none;
    public final ColorLED lightStrip;

    public leds() {
        lightStrip = new ColorLED(Constants.LEDConstants.LED_PORT, Constants.LEDConstants.LED_LENGTHS);

        // Configs
    }
    @Override
    public void periodic() {
        // This method will be called once per scheduler run
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void setColorNone() {
        ledColor = LedColor.none;
        lightStrip.none();
    }
    public void setColorRed() {
        ledColor = LedColor.red;
        lightStrip.red();
    }
    public void setColorOrange() {
        ledColor = LedColor.orange;
        lightStrip.orange();
    }
    public void setColorYellow() {
        ledColor = LedColor.yellow;
        lightStrip.yellow();
    }
    public void setColorBlue() {
        ledColor = LedColor.blue;
        lightStrip.blue();
    }
    public void setColorGreen() {
        ledColor = LedColor.green;
        lightStrip.green(); 
    }
    public void setColorGold() {
        ledColor = LedColor.gold;
        lightStrip.gold();
    }
    public void setColorWhite() {
        ledColor = LedColor.white;
        lightStrip.white();
    }
    public void setColorPurple() {
        ledColor = LedColor.purple;
        lightStrip.purple();
    }
    public void setColorRainbow() {
        ledColor = LedColor.rainbow;
        lightStrip.rainbow();
    }
}