// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.ColorLED;
import frc.robot.Constants;
import frc.robot.Robot;
import frc.robot.subsystems.ClimbSubsystem.LockdownMode;
// import frc.robot.subsystems.Climb.LockdownMode;

public class LedsSubsystem extends SubsystemBase {
    public enum LedColor {
        none, //no color, lights are off and the smartdashboard displays black.
        red,
            maroon,
        orange,
        yellow,
        green,
            lime,
        blue,
            lightblue,
        purple,
            pink,
            magenta,
        gold,
        white,
        rainbow,
        fasterfaster,
        climbProgressBar,
        redFlashing
    };
    public enum SubsystemUsingLEDS {
        drive,
        turret,
        shooter,
        climb,
        hopper,
        none
    };
    public String hexValue;

    public String[
    ] rainbowStrings = {
            "#000000", //none
            "#FF0000", //red
            "#0000FF", //blue
            "#00FF00", //green
            "#FFA500", //orange
            "#FFD700", //gold
            "#FFFFFF", //white
            "#FF00FF", //purple
            "#FF91FF", //pink
            "#FFFF00"  //yellow
    };

    public LedColor ledColor = LedColor.none;
    public SubsystemUsingLEDS usingSubsystem = SubsystemUsingLEDS.none;
    public final ColorLED lightStrip;

    public LedsSubsystem() {
        lightStrip = new ColorLED(Constants.LEDConstants.LED_PORT, Constants.LEDConstants.LED_LENGTHS);

        hexValue = "#000000";

        
        // Configs
    }
    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        SmartDashboard.putString("Subsystem Using LEDs", usingSubsystem.name());
        SmartDashboard.putString("LED Hex Value", lightStrip.getCurrentColor().toHexString());  
        if (ledColor == LedColor.rainbow || ledColor == LedColor.none) {
            lightStrip.rainbow();
        }
        if (ledColor == LedColor.fasterfaster) {
            lightStrip.fasterfaster();
        }
        if (ledColor == LedColor.redFlashing) {
            lightStrip.redFlashing();
        }
        // if (Robot.getInstance().m_climb.currentLockdownMode == LockdownMode.full) {
        //     lightStrip.redFlashing();
        // }
        // else if (Robot.getInstance().m_climb.currentLockdownMode == LockdownMode.partial) {
        //     lightStrip.red();
        // }
        // else{
            
        // }
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    //===============================================================================================================================================================================

    //priority from least to greatest: none, drive, hopper, turret, shooter, climb

    //rank 5
    public void noSubsystemUsingLeds() {
        if (usingSubsystem != SubsystemUsingLEDS.none && usingSubsystem != SubsystemUsingLEDS.climb && usingSubsystem != SubsystemUsingLEDS.shooter && usingSubsystem != SubsystemUsingLEDS.turret && usingSubsystem != SubsystemUsingLEDS.hopper && usingSubsystem != SubsystemUsingLEDS.drive) {
            usingSubsystem = SubsystemUsingLEDS.none;
        }
    }

    //rank 4
    public void driveTrainRequestingLeds() { // the ORs may need to be ANDs?
        if (usingSubsystem != SubsystemUsingLEDS.climb && usingSubsystem != SubsystemUsingLEDS.shooter && usingSubsystem != SubsystemUsingLEDS.turret && usingSubsystem != SubsystemUsingLEDS.hopper) {
            usingSubsystem = SubsystemUsingLEDS.drive;
        }
    }

    //rank 3
    public void hopperRequestingLeds() {
        if (usingSubsystem != SubsystemUsingLEDS.climb && usingSubsystem != SubsystemUsingLEDS.shooter && usingSubsystem != SubsystemUsingLEDS.turret) {
            usingSubsystem = SubsystemUsingLEDS.hopper;
        }
    }

    //rank 2
    public void turretRequestingLeds() {
        if (usingSubsystem != SubsystemUsingLEDS.climb && usingSubsystem != SubsystemUsingLEDS.shooter) {
            usingSubsystem = SubsystemUsingLEDS.turret;
        }
    }

    //rank 1
    public void shooterRequestingLeds() {
        if (usingSubsystem != SubsystemUsingLEDS.climb) {
            usingSubsystem = SubsystemUsingLEDS.shooter; 
        }
    }

    //rank 0
    public void climbRequestingLeds() { //nothing can override climb, this only sets the enum to climb
        if (usingSubsystem != SubsystemUsingLEDS.climb) {
            usingSubsystem = SubsystemUsingLEDS.climb; 
        }
    }

    //===============================================================================================================================================================================

    //red, orange, yellow, green, blue, purple, pink
    //white, gold, lightblue, magenta, lime, rainbow, none
    public void setColorNone() {
        ledColor = LedColor.none;
        lightStrip.none();
        hexValue = "#000000";
    }
    public void setColorRed() {
        ledColor = LedColor.red;
        lightStrip.red();
        hexValue = "#FF0000";
    }
    public void setColorMaroon() {
        ledColor = LedColor.maroon;
        lightStrip.maroon();
        hexValue = "#800000";
    }
    public void setColorOrange() {
        ledColor = LedColor.orange;
        lightStrip.orange();
        hexValue = "#FFA500";
    }
    public void setColorYellow() {
        ledColor = LedColor.yellow;
        lightStrip.yellow();
        hexValue = "#FFFF00";
    }
    public void setColorGreen() {
        ledColor = LedColor.green;
        lightStrip.green(); 
        hexValue = "#117d00";
    }
    public void setColorLime() {
        ledColor = LedColor.lime;
        lightStrip.lime(); 
        hexValue = "#00FF00";
    }
    public void setColorBlue() {
        ledColor = LedColor.blue;
        lightStrip.blue();
        hexValue = "#0000FF";
    }
    public void setColorLightBlue() {
        ledColor = LedColor.lightblue;
        lightStrip.lightblue();
        hexValue = "#00FFFF";
    }
    public void setColorPurple() {
        ledColor = LedColor.purple;
        lightStrip.purple();
        hexValue = "#800080";  
    }
    public void setColorWhite() {
        ledColor = LedColor.white;
        lightStrip.white();
        hexValue = "#FFFFFF";
    }
    public void setColorPink() {
        ledColor = LedColor.pink;
        lightStrip.pink();
        hexValue = "#FF91FF";
    }
    public void setColorMagenta() {
        ledColor = LedColor.magenta;
        lightStrip.pink();
        hexValue = "#ff00ff";
    }
    public void setColorGold() {
        ledColor = LedColor.gold;
        lightStrip.gold();
        hexValue = "#FFD700";
    }
    public void setModeRainbow() {
        ledColor = LedColor.rainbow;
    }
    public void setModeFasterFaster() {
        ledColor = LedColor.fasterfaster;
    }
    public void setModeClimbProgressBar() {
        ledColor = LedColor.climbProgressBar;
        lightStrip.climbProgressBar();
    }
    public void setModeRedFlashing() {
        ledColor = LedColor.redFlashing;
        //lightStrip.redFlashing();
    }
}