// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.Constants;
import frc.robot.subsystems.HopperSubsystem;
import frc.robot.subsystems.LedsSubsystem;
import edu.wpi.first.wpilibj.Timer;
public class Agitate extends Command {
    private final HopperSubsystem m_hopper;
    private final LedsSubsystem m_leds;
    private final Timer m_timer = new Timer();
    public Agitate(HopperSubsystem subsystem, LedsSubsystem ledSubsystem)  {
        m_hopper = subsystem;
        m_leds = ledSubsystem;
        addRequirements(m_hopper);
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        if (Constants.Debug.DEBUG_MODE) {
            System.out.println("Agitating");
        }
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        m_timer.start();
        if (m_timer.get() < 0.5) {
            m_hopper.forwardForAgitate();
        }
        else if ((m_timer.get() > 0.5) && (m_timer.get() < 1)) {
            m_hopper.reverseForAgitate();
        }
        else if (m_timer.get() > 1){
            m_timer.reset();
        }
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_hopper.stopHopperFloorTransferSecure();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
