// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.subsystems.Hopper;
import frc.robot.subsystems.LedsSubsystem;

public class AutonExtend extends Command {
private final Hopper m_hopper;
private final LedsSubsystem m_leds;


    public AutonExtend(Hopper hopper, LedsSubsystem m_leds) {
        m_hopper = hopper;
        addRequirements(m_hopper);
        this.m_leds = m_leds;
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_hopper.setHopperExtend();
        m_leds.hopperRequestingLeds();
        if (m_leds.usingSubsystem == LedsSubsystem.SubsystemUsingLEDS.hopper) {
            m_leds.setColorWhite();
        }
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {}

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_leds.setColorNone();
        m_leds.noSubsystemUsingLeds();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return m_hopper.isHopperExtended();
    }

}
