// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.Constants;
import frc.robot.subsystems.Hopper;

public class AutonExtend extends Command {
private final Hopper m_hopper;

    public AutonExtend(Hopper hopper) {
        m_hopper = hopper;
        addRequirements(m_hopper);
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_hopper.setHopperExtend();
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        m_hopper.setFuelGrabberSpeed();
        m_hopper.setHopperFloorTransferSecureSpeed(Constants.HopperConstants.HopperFloorTransferSecureSpeed);
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
