// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.Constants;
import frc.robot.subsystems.Hopper;
import frc.robot.subsystems.LedsSubsystem;
import frc.robot.subsystems.Shooter;
import frc.robot.subsystems.Turret;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class CenterShootCommand extends Command {
    private final Shooter m_shooter;
    private final Turret m_turret;
    private final Hopper m_hopper;
    private final LedsSubsystem m_leds;
    private final double m_rpm;
    private final Timer m_timer = new Timer();
    private Alliance myAlliance;
    private double targetAngle;

    public final double agitateForwardTime = 0.75;
    public final double agitateReverseTime = 0;

    public CenterShootCommand(double rpm, Shooter shooterSubsystem, Hopper hopperSubsystem, LedsSubsystem ledSubsystem, Turret turretSubsystem) {
        m_rpm = rpm;
        m_shooter = shooterSubsystem;
        m_turret = turretSubsystem;
        // why is hopper not in the requirements list
        m_hopper = hopperSubsystem;
        m_leds = ledSubsystem;
        addRequirements(m_shooter, m_turret);
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_timer.reset();

        m_leds.shooterRequestingLeds();
        if (m_leds.usingSubsystem == LedsSubsystem.SubsystemUsingLEDS.shooter) {
            m_leds.setColorRed();
        }
        m_shooter.setTargetRPM(m_rpm);

        myAlliance = Constants.DriveConstants.MyAlliance();

        targetAngle = myAlliance == Alliance.Red ? 0.0 : 180.0;
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        m_turret.aimDegrees(Constants.TurretShooterConstants.MAX_LEFT_DEGREES);
        m_turret.aimFieldRelativeAngle(targetAngle);

        m_shooter.spinShooter(m_shooter.targetRPM);
        m_hopper.setFuelGrabberSpeed();

        if (m_shooter.isAtTargetRPM()) {
            if (m_timer.isRunning()) {
                m_timer.stop();
            }
            m_shooter.runGate(Constants.TurretShooterConstants.gateForwardSpeed);
            m_shooter.runMagazine(Constants.TurretShooterConstants.magazineForwardSpeed);
            m_hopper.setHopperFloorTransferSecureSpeed(Constants.IntakeHopperConstants.HopperFloorTransferSecureSpeed);
        } else {
            if (!m_timer.isRunning() || m_timer.hasElapsed(agitateForwardTime + agitateReverseTime)) {
                m_timer.restart();
            }

            m_shooter.stopMagazine();
            if (!m_timer.hasElapsed(agitateForwardTime)) {

                m_shooter.runGate(Constants.TurretShooterConstants.gateForwardSpeed);
                m_hopper.setHopperFloorTransferSecureSpeed(Constants.IntakeHopperConstants.AGITATE_COMMAND_SPEED);

            } else {
                m_shooter.runGate(Constants.TurretShooterConstants.gateReverseSpeed);
                m_hopper.setHopperFloorTransferSecureSpeed(-Constants.IntakeHopperConstants.AGITATE_COMMAND_SPEED);
            }
        }
        
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_timer.stop();

        m_hopper.stopAll();
        m_shooter.stopAll();

        m_leds.setColorNone();
        m_leds.noSubsystemUsingLeds();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
