// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.Constants;
import frc.robot.subsystems.ClimbSubsystem;
import frc.robot.subsystems.LedsSubsystem;
public class ClimbRaiseAuto extends Command {
    private final ClimbSubsystem m_climb;
    private final LedsSubsystem m_leds;

    public ClimbRaiseAuto(ClimbSubsystem subsystem, LedsSubsystem leds)  {
        m_climb = subsystem;
        m_leds = leds;
        addRequirements(m_climb);
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        if (Constants.Debug.DEBUG_MODE) {
            System.out.println("+---------------------+");
            System.out.println("| Auto Climb Engaging |");
            System.out.println("+---------------------+");
        }
        m_leds.climbRequestingLeds();
        if (m_leds.usingSubsystem == LedsSubsystem.SubsystemUsingLEDS.climb) {
            m_leds.setColorLime();
        }
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        m_climb.setUpperPosition();
        if (Constants.Debug.DEBUG_MODE) {System.out.println("Raising Climb...");}
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        if (Constants.Debug.DEBUG_MODE) {System.out.println("Auto incrementing climb stage...");}
        m_climb.climbStageIncrement();
        m_climb.setTop();
        m_leds.setColorNone();
        m_leds.noSubsystemUsingLeds();
        if (Constants.Debug.DEBUG_MODE) {
            System.out.println("+------------------------+");
            System.out.println("| Auto Climb Disengaging |");
            System.out.println("+------------------------+");
            System.out.println("=");
        }
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return m_climb.isRaised();
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
