// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.Command;
import java.util.function.DoubleSupplier;

import frc.robot.ColorLED;
import frc.robot.Constants;
import frc.robot.Robot;
import frc.robot.RobotContainer;
import frc.robot.subsystems.climb;
import frc.robot.subsystems.leds;


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Climb extends Command {
    ColorLED lightStrip;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private final climb m_climb;
    private final leds m_leds;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
   
    public Climb(climb subsystem, leds ledSubsystem)  {
        m_climb = subsystem;
        m_leds = ledSubsystem;
        addRequirements(m_climb);
        addRequirements(m_leds);
    

        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // m_subsystem = subsystem;
        // addRequirements(m_subsystem);    

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        System.out.println("+----------------+");
        System.out.println("| Climb engaging |");
        System.out.println("+----------------+");
        System.out.println("Mode:");
        if (!m_climb.isClimbing()) {   
            m_leds.setColorPurple();
            System.out.println("<<<< Climbing up >>>>");
            System.out.println("<");
            System.out.println("<");
        }
        else {
            m_leds.setColorPink();
            System.out.println(">>>> Climbing down <<<<");
            System.out.println(">");
            System.out.println(">");
        }
        System.out.println("Lights on");
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        if (!m_climb.isClimbing()) {
            m_climb.setUpperPosition();           
            /*System.out.println("<<<< Climbing up >>>>");
            System.out.println("<");
            System.out.println("<");*/
        }
        else {
            m_climb.setLowerPosition();
            /*System.out.println(">>>> Climbing down <<<<");
            //System.out.println("Arm is already up! Cannot extend!");
            System.out.println(">");
            System.out.println(">");*/
        }
        
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_climb.toggleClimbing();
        System.out.println("+-------------------+");
        System.out.println("| Climb disengaging |");
        System.out.println("+-------------------+");
        System.out.println("=");
        System.out.println("Incrementing climb stage...");
        m_climb.climbStageIncrement();
        System.out.println("Disabling lights...");
        m_leds.setColorNone();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return m_climb.isRaised();
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
