// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.ColorLED;
import frc.robot.Constants;
import frc.robot.subsystems.Hopper;
import frc.robot.subsystems.LedsSubsystem;
import frc.robot.subsystems.Shooter;
import frc.robot.subsystems.ClimbSubsystem;


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Idle extends Command {
    ColorLED lightStrip;
    private final Hopper m_hopper;
    private final Shooter m_shooter;
    private final LedsSubsystem m_leds;
    private final ClimbSubsystem m_climb;
    
    public Idle(Hopper hopperSubsystem, Shooter shooterSubsystem, LedsSubsystem ledSubsystem, ClimbSubsystem climbSubsystem)  {
        m_hopper = hopperSubsystem;
        m_shooter = shooterSubsystem;
        m_leds = ledSubsystem;
        m_climb = climbSubsystem;
        addRequirements(m_hopper);
        addRequirements(m_shooter);
        addRequirements(m_climb);
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_hopper.setHopperFloorTransferSecureSpeed(0.4);
        m_shooter.setIdling();
        m_climb.shutdownClimb();
        if (Constants.Debug.DEBUG_MODE) {
            System.out.println("Idle");
        }
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {}

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {}

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return true;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
