// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.subsystems.Hopper;

public class Retract extends Command {
    private final Hopper m_subsystem;
    public Retract(Hopper subsystem) {
        m_subsystem = subsystem;
        // Use addRequirements() here to declare subsystem dependencies.
        addRequirements(m_subsystem);
    
    }


    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_subsystem.setHopperRetract();
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
    
}

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return m_subsystem.isHopperRetracted();
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
